baseURL: "https://www.the-sprawl.blog/"
languageCode: "en-us"
theme: "PaperMod"

title: "the Sprawl"
description: "TODO description"


params:
    ShowShareButtons: true
    ShowReadingTime: true
    
      # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"
        
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
