baseURL: "https://www.the-sprawl.blog/"
languageCode: "en-us"
theme: "PaperMod"
author:
  TabTwo:
    name: "Ralph J.Mayer"
    twitter: "tabtwo"

title: "the Sprawl"
description: "TODO description"


params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: "twitter"
            url: "https://twitter.com/TabTwo"
            
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
